<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Ashifs-MBP-2.fios-router.home" name="com.sample.test.demo.tests.PizzaOrderTest" tests="6" failures="1" timestamp="07 May 2019 16:31:34 GMT" time="0.811" errors="0">
  <testcase name="validateEmail" time="0.260" classname="com.sample.test.demo.tests.PizzaOrderTest"/>
  <testcase name="vaarifyQuantity" time="0.166" classname="com.sample.test.demo.tests.PizzaOrderTest"/>
  <testcase name="validateOrder" time="0.120" classname="com.sample.test.demo.tests.PizzaOrderTest"/>
  <testcase name="selectPizza" time="0.075" classname="com.sample.test.demo.tests.PizzaOrderTest"/>
  <testcase name="validatePayment" time="0.150" classname="com.sample.test.demo.tests.PizzaOrderTest"/>
  <testcase name="validateDialog" time="0.040" classname="com.sample.test.demo.tests.PizzaOrderTest">
    <failure type="java.lang.AssertionError" message="expected [Missing email] but found []">
      <![CDATA[java.lang.AssertionError: expected [Missing email] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.sample.test.demo.tests.PizzaOrderTest.validateDialog(PizzaOrderTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateDialog -->
</testsuite> <!-- com.sample.test.demo.tests.PizzaOrderTest -->
